# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(default=b'1', max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=b'1', max_length=15),
        ),
    ]
