# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20170402_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='permission',
            field=models.IntegerField(default=3),
        ),
    ]
