# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20170415_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permission',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
